### PR TITLE
Issue-588: Holistic review of non-quarkus setup chapter

### LINKED ISSUE #588: Holistic review of non-quarkus setup chapter
**Goal**
Holistic review of non-quarkus [setup guides](https://sonataflow.org/serverlessworkflow/main/getting-started/learning-environment.html)

### PR DESCRIPTION
**Pull request by LuboTerifaj**
Closes/Fixes/Resolves #588 

**Holistic review of non-quarkus setup chapter**

The PR updates some issues found during the chapter review.

 There was identified one issue that is **out of the scope** if this PR: https://github.com/apache/incubator-kie-kogito-docs/issues/647

### CODE REVIEW

**Comment by LuboTerifaj** [comment]
fyi @kaldesai

**Review by ricardozanini — COMMENTED** [review]
@domhanak this indeed solves the problem regarding the kn plugin installation. Although, I remember reading that the procedure was "scattered" along the documentation. So we would need to remove another branches too. I'm curious why this procedure would be in any other places than that. Additionally, we could use `includes` if that's the case.

**Comment by domhanak** [comment]
@LuboTerifaj if you do not know the details, how did you validate the bits that use it?

**Comment by tomasdavidorg** [comment]
From the community perspective, there is currently no change in the community release process and as far as I know the last community release is the 0.32.0. For the 10 release we should update the documentation according to the changes of the community release process (if there are any). https://issues.redhat.com/browse/KOGITO-9989

I don't know how the community will be released and I also didn't find any jira/issue which covers this. I think this is a gap that we need to fix.

From the product perspective there is jira https://issues.redhat.com/browse/SRVLOGIC-332.

**Comment by LuboTerifaj** [comment]
Hello @domhanak , I validated the documentation with the current state, not the next release.

**Comment by domhanak** [comment]
@LuboTerifaj I am asking to confirm this is up to date with latest changes of kn cli ( meaning that if I go here - https://github.com/apache/incubator-kie-tools/tree/main/packages/kn-plugin-workflow - check it out and build it, it matches. Because you wrote `the documentation reflects how it is working with the most recent release.` and most recent release is from December which is not good. So does the `current state` mean `main` branch please?

**Comment by LuboTerifaj** [comment]
Hi @domhanak ,

The set-up chapter doesn't contain any section regarding kn-plugin. There is only a reference to different section: https://sonataflow.org/serverlessworkflow/main/testing-and-troubleshooting/kn-plugin-workflow-overview.html.

When I followed the instructions in the section, I was able to install the kn plugin as described in the documentation. Any changes needed for kn plugin are tracked by the issues @tomasdavidorg mentioned above. If you think it is necessary to perform any other tasks related to kn plugin in the documentation, feel free to report a new issue for that.

Thanks!

**Review by domhanak — APPROVED** [review]

**Comment by domhanak** [comment]
@LuboTerifaj Issues Tomas mentions are irrelevant in Apache KIE community, the KOGITO jira is deprecated since September 2023 and my question is still not answered. Anyway let's merge I give up asking the same again and again

**Comment by LuboTerifaj** [comment]
Hello @domhanak , thank you for merging.

I tried to provide as much information as possible. The updates for kn plugin are indeed tracked. How it is being tracked is a different problem. I am not sure what question I didn't answer. So let's recap.

To your questions:

- "Is this updated to include the latest kn cli updates and how it will be when we release apache 10.0.0 kn workflow?"
  - Answered in https://github.com/apache/incubator-kie-kogito-docs/pull/648#issuecomment-2160500648
- "If you do not know the details, how did you validate the bits that use it?"
  - Validating the bits using main branch was not the goal of the documentation review. I did validate the latest released bits (0.32.0). We should not advise users to build the plugin by themselves from main.
- "Also latest release means 0.32.0?"
  - Yes.
- "So does the current state mean main branch please?"
  - No. The current state means using the latest release (0.32.0).

Any changes made to main that could affect the documentation should be reported to the documentation team by the issue assignee. In this way we ensure the changes will get to the documentation.
Updating kn workflow plugin set-up in the documentation is currently tracked by https://issues.redhat.com/browse/KOGITO-9989. I understand the KOGITO jira is deprecated, but it's not so far in the past we were using that jira for the issues and I don't think we already migrated all the issues to Apache github issues. In addition, some community members may forgot or not be aware of it, and report the issue in deprecated KOGITO jira. Anyway, I reported the issue also here to properly track it in Apache community:

- https://github.com/apache/incubator-kie-kogito-docs/issues/661

I hope this clarifies your concerns/questions.

**Pull request merged**
